name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the publish-hello-docker-image Docker image
        run: |
          docker login --username ${{ secrets.GIT_USER }} --password ${{ secrets.GIT_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/py405/publish-hello-docker-image:latest
          docker run ghcr.io/py405/publish-hello-docker-image:latest
          docker push ghcr.io/py405/publish-hello-docker-image:latest
