name: publish
on: [push]
jobs:
  publish-docker-image-to-github-container-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the publish-docker-image-to-github-container-registry Docker image
        run: |
          docker login --username ${{ secrets.GIT_USER }} --password ${{ secrets.GIT_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/py405/publish-docker-image-to-github-container-registry:latest
          docker run ghcr.io/py405/publish-docker-image-to-github-container-registry:latest
          docker push ghcr.io/py405/publish-docker-image-to-github-container-registry:latest
