name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
      - name: Build the publish-hello-docker-image Docker image
        run: |
          docker login --username ${{ secrets.GIT_USER }} --password ${{ secrets.GIT_TOKEN }} ghcr.io
          docker build . --tag publish-hello-docker-image:latest
          docker run publish-hello-docker-image:latest
          docker push publish-hello-docker-image:latest
